# -*- coding: utf-8 -*-
"""trabalho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mV7oJKpoXU0ieeTIUX9kpk4rCbV7HFTr
"""

import pandas as pd
import plotly.express as px
import streamlit as st 

#streamlit run codigoBase.py

#LENDO O DATASET
df = pd.read_csv('https://raw.githubusercontent.com/fjcorreiaa/DataTrabalho/main/ipeadata-T1-2021', sep=',')

#MELHORANDO O NOME DAS COLUNAS DA TABELA
df = df.rename(columns={'Rendimento médio real - todos trab. - efetivo - mensal (2021 T1)': 'Rendimento médio real', 'Pessoas ocupadas (2021 T1)': 'Pessoas ocupadas', 'Pessoas desocupadas (2021 T1)': 'Pessoas desocupadas' })

#CRIANDO LISTA REGIÃO

Regiao = {
    "Norte":['AM', 'PA', 'RR', 'AC','RO','AP', 'TO'],
    "Sul":['PR', 'SC', 'RS'],
    "Centro Oeste":['MT', 'MS', 'GO', 'DF'],
    "Nordeste":['BA', 'CE','MA', 'PB', 'PE', 'RN', 'SE', 'AL', 'PI'],
    "Sudeste":['SP', 'RJ', 'MG','ES'],
}
for k in Regiao:
    df.loc[ df['Sigla'].isin(Regiao[k]), 'Regiao'] = k


#SELECÃO DA REGIÃO
regioes = list(df['Regiao'].unique())
state = st.sidebar.selectbox('Qual região?', regioes)

#SELEÇÃO DA COLUNA
#column ='Pessoas ocupadas'
colunas = ['Pessoas ocupadas','Pessoas desocupadas','Rendimento médio real']
column = st.sidebar.selectbox('Qual tipo de informação?', colunas)

#SELEÇÃO DAS LINHAS QUE PERTECEM A REGIAO 
df = df[df['Regiao'] == Regiao]

fig = px.bar (df, x="Estado", y=column, title=column + ' - ')
fig.update_layout( xaxis_title='Estados', yaxis_title=column.upper(), title = {'x':0.5})

st.title('Pessoas Ocupadas e Desocupadas no Brasil - 2021')
st.write('Nessa aplicação, o usuário tem a opção de escolher o estado e o tipo de informação para mostrar o gráfico. Utilize o menu lateral para alterar a mostragem.')

st.plotly_chart(fig, use_container_width=True)

st.caption('Os dados foram obtidos a partir do Instituto de Pesquisa Econômica Aplicada (IPEA)')
